import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // 👇 튕김 방지 설정을 '가장 바깥 틀'에 적용
    <html lang="ko" className="overflow-y-scroll">
      {/* 👇 기본 테마(배경/글자색)를 '내부'에 적용 */}
      <body className={`${inter.className} bg-white text-gray-900 dark:bg-[#121212] dark:text-gray-200 transition-colors duration-300`}>
        {children}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "김작가의 서재",  // 👈 여기에 탭에 뜰 이름을 적으세요
  description: "웹소설과 시나리오를 쓰는 공간입니다.", // 👈 검색엔진 설명
};


